### ISSUE TITLE
Failed to execute the build 'FOO-1': null value in entry: resolverSharedCredentialsPassword=null

### ISSUE THREAD

**Issue by ctl-eng-tools** [jfrog/bamboo-artifactory-plugin#132]
Hello!

We are using Bamboo 7.2.1 (hosted on Windows Server 2012 R2) with Bamboo Artifactory Plugin 3.2.0 and are getting the following error when using an Artifactory Generic Resolve task:

**Failed to execute the build 'FOO-1': null value in entry: resolverSharedCredentialsPassword=null**

The Bamboo Artifactory Plugin is able to connect to Artifactory server with the username and password we supply.

Also, even if we use known good credentials in the Override Credentials section of the task, we get the same error.

We recently upgraded Bamboo and by necessity, the Bamboo Artifactory Plugin.

Almost forgot to mention that we are using Artifactory Professional 6.21.0.

Regards,

-CET

**Comment by yahavi** [comment]
@ctl-eng-tools 
Thanks for reporting this issue! We fixed It by #133. 
Here is a snapshot with the fix:
 https://oss.jfrog.org/oss-snapshot-local/org/jfrog/bamboo/bamboo-artifactory-plugin/3.2.x-SNAPSHOT/bamboo-artifactory-plugin-3.2.x-20201225.150534-4.jar

We'd appreciate your feedback on that!

**Comment by ctl-eng-tools** [comment]
Thanks for fixing this -- the Artifactory Generic Resolve task now works!

**Comment by yahavi** [comment]
@ctl-eng-tools,
Bamboo Artifactory plugin 3.2.1 is released. This version includes a fix for this issue.
Feel free to upgrade.
