### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString

### ISSUE THREAD

**Issue by holle** [jfrog/bamboo-artifactory-plugin#140]
The Bamboo Artifactory Plugin version 3.2.1 has the error as described here:

https://www.jfrog.com/jira/projects/HAP/issues/HAP-1442

```
error	22-Feb-2021 13:02:46	[main] ERROR org.jfrog.build.extractor.maven.BuildInfoRecorder - org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
error	22-Feb-2021 13:02:46	java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
error	22-Feb-2021 13:02:46	    at org.jfrog.build.extractor.ModuleParallelDeployHelper.deployArtifacts (ModuleParallelDeployHelper.java:37)
error	22-Feb-2021 13:02:46	    at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deploy (BuildDeploymentHelper.java:88)
```

I forgot:

Running Atlassian Bamboo 7.1.4
Running with jdk1.8.0_241-amd64 (Oracle)

**Comment by yahavi** [comment]
@holle,
Thanks for reporting this issue.

We fixed the issue in [HAP-1442](https://www.jfrog.com/jira/browse/HAP-1442) with https://github.com/jfrog/build-info/pull/450.

Here is a snapshot which includes the fix:
https://oss.jfrog.org/oss-snapshot-local/org/jfrog/bamboo/bamboo-artifactory-plugin/3.2.x-SNAPSHOT/bamboo-artifactory-plugin-3.2.x-20210222.133326-15.jar

We'd appreciate your feedback on that.

**Comment by holle** [comment]
Hi @yahavi 

the snapshot 3.2.x-20210222.133326-15 seems to work.
I was able to recompile the maven projects and deply the build results and capture the build info in artifactory.

Thanks for the quick reply.
Cheers,
Holger
