### ISSUE TITLE
NullPointerException while executing task

### ISSUE THREAD

**Issue by RaghvendraGarg** [jfrog/bamboo-artifactory-plugin#148]
**Describe the bug**
When running the maven task plugin fails with NPE.
Bamboo 7.2.5 and plugin version 3.2.3

`Error occurred while running Task 'Publish deployable artifacts to Artifactory(15)' of type org.jfrog.bamboo.bamboo-artifactory-plugin:maven3Task.
--
23-Aug-2021 12:28:02 | java.lang.NullPointerException
23-Aug-2021 12:28:02 | at org.jfrog.bamboo.builder.BuilderDependencyHelper.downloadDependenciesAndGetPath(BuilderDependencyHelper.java:61)
23-Aug-2021 12:28:02 | at org.jfrog.bamboo.task.ArtifactoryMaven3Task.extractMaven3Dependencies(ArtifactoryMaven3Task.java:323)
23-Aug-2021 12:28:02 | at org.jfrog.bamboo.task.ArtifactoryMaven3Task.runTask(ArtifactoryMaven3Task.java:87)
23-Aug-2021 12:28:02 | at org.jfrog.bamboo.task.ArtifactoryTaskType.execute(ArtifactoryTaskType.java:46)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$2(TaskExecutorImpl.java:321)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:258)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:321)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:118)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:73)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.executeBuildPhase(DefaultBuildAgent.java:190)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:162)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.lambda$waitAndPerformBuild$0(BuildAgentControllerImpl.java:137)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:118)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:130)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.lambda$start$0(DefaultBuildAgent.java:110)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
23-Aug-2021 12:28:02 | at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
23-Aug-2021 12:28:02 | at java.lang.Thread.run(Thread.java:748)`

Build process command:
`/opt/data/services/jdks/1.8.0_201/bin/java -classpath /opt/data/bamboo/agent_capabilities/apache-maven-3.2.3/boot/plexus-classworlds-2.5.1.jar -Dclassworlds.conf=/opt/data/bamboo/agent_capabilities/apache-maven-3.2.3/bin/m2.conf -Dmaven.home=/opt/data/bamboo/agent_capabilities/apache-maven-3.2.3 org.codehaus.plexus.classworlds.launcher.Launcher --batch-mode -Djava.io.tmpdir=/tmp/INFRA-DEP-JOB1 org.codehaus.mojo:versions-maven-plugin:1.2:set -DnewVersion=1.0.1207 -Dmaven.repo.local=/opt/data/bamboo/bamboo-agent-home/xml-data/build-dir/INFRA-DEP-JOB1/m2`

**Comment by Joyvalley** [comment]
Hi, 
we are having a similar problem also running bamboo 7.2.5 and plugin version 3.2.3 
<html>
<body>


02-Sep-2021 11:22:29 | Starting task 'Build' of type 'org.jfrog.bamboo.bamboo-artifactory-plugin:maven3Task'
-- | --
02-Sep-2021 11:22:29 | Error occurred while running Task 'Build(2)' of type org.jfrog.bamboo.bamboo-artifactory-plugin:maven3Task.
02-Sep-2021 11:22:29 | java.lang.NullPointerException
02-Sep-2021 11:22:29 | at org.jfrog.bamboo.builder.MavenDataHelper.setResolverProperties(MavenDataHelper.java:95)
02-Sep-2021 11:22:29 | at org.jfrog.bamboo.builder.MavenDataHelper.setClientData(MavenDataHelper.java:54)
02-Sep-2021 11:22:29 | at org.jfrog.bamboo.builder.MavenAndIvyBuildInfoDataHelperBase.setBuilderData(MavenAndIvyBuildInfoDataHelperBase.java:189)
02-Sep-2021 11:22:29 | at org.jfrog.bamboo.builder.MavenAndIvyBuildInfoDataHelperBase.<init>(MavenAndIvyBuildInfoDataHelperBase.java:77)
02-Sep-2021 11:22:29 | at org.jfrog.bamboo.builder.MavenDataHelper.<init>(MavenDataHelper.java:33)
02-Sep-2021 11:22:29 | at org.jfrog.bamboo.task.ArtifactoryMaven3Task.initTask(ArtifactoryMaven3Task.java:69)
02-Sep-2021 11:22:29 | at org.jfrog.bamboo.task.ArtifactoryTaskType.execute(ArtifactoryTaskType.java:37)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$2(TaskExecutorImpl.java:321)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:258)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:321)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:118)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:73)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.executeBuildPhase(DefaultBuildAgent.java:190)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:162)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.lambda$waitAndPerformBuild$0(BuildAgentControllerImpl.java:137)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:118)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:130)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.lambda$start$0(DefaultBuildAgent.java:110)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
02-Sep-2021 11:22:29 | at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)


</body>
</html>

Disabling the build info makes the build run again. 

Kind regards,
JF

**Comment by shriniwaspatwardhan** [comment]
We have a solution and a PR for this will be opened tomorrow. the NPE  downloadDependenciesAndGetPath method on line  61 occurs when tmp.directory value is empty or points to a non-existing directory.

**Comment by yahavi** [comment]
@shriniwaspatwardhan 
Bamboo Artifactory plugin 3.2.4 is released. This version includes the fix.
We'd appreciate your feedback on that.
