### ISSUE TITLE
Version Compatibility Mismatch in User Guide vs Marketplace

### ISSUE THREAD

**Issue by bkr-usda** [jfrog/bamboo-artifactory-plugin#154]
For the latest version of the plugin, 3.2.3, the official [jfrog documentation](https://www.jfrog.com/confluence/display/JFROG/Bamboo+Artifactory+Plug-in) shows it as compatible with "Bamboo 7.1.3 - 8.0.x".

However the [Marketplace listing](https://marketplace.atlassian.com/apps/27818/artifactory-for-bamboo?tab=versions&hosting=server) shows 3.2.3 is compatible with "Bamboo Server 7.2.5 - 8.0.4".

**Comment by eyalbe4** [comment]
Right @bkr-usda, the plugin is assumed to be compatible with all 8.0.x patches, including the one

**Comment by eyalbe4** [comment]
Right @bkr-usda, the plugin is assumed to be compatible with all 8.0.x patches, including future patches, like 8.0.5, 8.0.6 and so on.

**Comment by bkr-usda** [comment]
Sorry, I'll be more clear:

Is the 3.2.3 version of the plugin compatible with Bamboo 7.1.3 to 7.2.4? If so, can the versions tagged in the Marketplace listing get corrected so folks on those versions of Bamboo will see that there is an update available via the Manage Apps page in Bamboo?
