### ISSUE TITLE
Could not execute task 'Upload Release Artifact to Artifactory server

### ISSUE THREAD

**Issue by mandevs** [jfrog/bamboo-artifactory-plugin#169]
**Describe the bug**
We are facing issue with artifactory plugin while trying to upload the release artifact to the JFrog artifactory server. While trying to build our release artifact it is giving error as "Could not execute task 'Upload Release Artifact to Artifactory server' no Plugin with key 'org.jfrog.bamboo.bamboo-artifactory-plugin:artifactoryGenericTask' is installed."

I checked the Remote Agent which is running this and I can see the plugin jar inside the user installed plugin. Could you please help here?
---------------------------------

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Versions**
- Bamboo Artifactory plugin version: 3.2.2
- Bamboo operating system: Windows
- Artifactory Version: 7.27.3

**Additional context**
here is the error trace 

simple	25-Jan-2022 07:33:12	Starting task 'Download artifact' of type 'com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:artifactdownloadertask'
simple	25-Jan-2022 07:33:12	Preparing to download plan result EASDSW-BUIL-1773 artifact: Non required shared artifact: [Yukon Installer], pattern: [*.zip] anchored at: [yukon-build/dist]
simple	25-Jan-2022 07:33:45	Artifact [Yukon Installer] downloaded successfully in 32.91 s to working directory
simple	25-Jan-2022 07:33:45	Finished task 'Download artifact' with result: Success
error	25-Jan-2022 07:33:45	Could not execute task 'Test' no Plugin with key 'org.jfrog.bamboo.bamboo-artifactory-plugin:artifactoryGenericTask' is installed.
simple	25-Jan-2022 07:33:45	Running post build plugin 'Docker Container Cleanup'
simple	25-Jan-2022 07:33:45	Running post build plugin 'NCover Results Collector'
simple	25-Jan-2022 07:33:45	Running post build plugin 'Clover Results Collector'
simple	25-Jan-2022 07:33:45	Running post build plugin 'npm Cache Cleanup'
simple	25-Jan-2022 07:33:45	Running post build plugin 'PBC: Stop Container Agent'
simple	25-Jan-2022 07:33:45	Running post build plugin 'Artifact Copier'
simple	25-Jan-2022 07:33:45	Finalising the build...

**Comment by yahavi** [comment]
@mandevs,
Thanks for reporting this issue!

As it looks, the plugin is not installed on your agent. This may occur due to many reasons. Please try to reinstall the plugin and check the agent's logs.

For example, one possible reason is the lack of memory in the agent. If you see errors such as:

    INFO | jvm 1 | 2020/11/10 11:12:36 | 2020-11-10 11:12:36,120 ERROR [remoteEventRebroadcasterMessageListenerContainer-1] [ScanningPluginLoader] Unable to deploy plugin 'org.jfrog.bamboo.bamboo-artifactory-plugin' from 'Unit: /Users/yahavi/bamboo-agent-home/plugins/user-installed/plugin_8527020839401694412_bamboo-artifactory-plugin-3.1.0.jar (1604999532000)'.
    INFO | jvm 1 | 2020/11/10 11:12:36 | 2020-11-10 11:12:36,121 ERROR [remoteEventRebroadcasterMessageListenerContainer-1] [ScanningPluginLoader] Because of the following exception:
    INFO | jvm 1 | 2020/11/10 11:12:36 | java.lang.OutOfMemoryError: GC overhead limit exceeded

That means your agent has insufficient heap size. I'd recommend the resolution in this guide: https://confluence.atlassian.com/bamkb/outofmemory-errors-in-bamboo-server-or-in-remote-agent-307038120.html

Please let me know if it helped.

**Comment by mandevs** [comment]
@yahavi, 

I have tried to disable/enable the plugin also reinstall/updated to the latest compatible version but still getting the same error. Could you please help here?

![Capture](https://user-images.githubusercontent.com/16577127/160336713-0ec15689-6b21-45a7-88b3-6f804bcced80.JPG)

**Comment by yahavi** [comment]
@mandevs,
Thanks for your input.
Did you try adding memory to the agent? It usually ends up with it. Do you see the `java.lang.OutOfMemoryError` anywhere in the server logs?

**Comment by mandevs** [comment]
Hi @yahavi,
This has been resolved by increasing agent heap memory.

Thanks,
Vish
