### ISSUE TITLE
Artifactory Nuget build task not setting build.name and build.number properties on push

### ISSUE THREAD

**Issue by tobmat** [jfrog/bamboo-artifactory-plugin#176]
**Is your feature request related to a problem? Please describe.**
Not sure if this is a feature request or an actual bug.  Issue is that pushed artifacts need build.name and build.number properties set for proper repo path for artifacts to be available from artifactory build screen.

**Describe the solution you'd like to see**
Would like to see build.name and build.number property fields set on artifacts in addition to the nuget.* properties that are being set when Capture Build is selected on 'Artifactory Nuget' task set to push.

**Describe alternatives you've considered**
Currently only alternative would be to manually add these properties or add it via api calls after the push task.

**Additional context**
- Shows artifact properties screen of what is currently being set.  Missing build.name and build.number.
<img width="484" alt="artifactory-properties" src="https://user-images.githubusercontent.com/8656463/162244300-06fad70f-788e-4be2-a316-135c82f4c8de.png">
- Shows build, published modules, artifact screen where repo path is not set.
<img width="838" alt="artifactory-build-repo-path" src="https://user-images.githubusercontent.com/8656463/162244309-a7f341d3-5469-4e3b-92ae-63c33b7fd741.png">

**Comment by RobiNino** [comment]
Hi @tobmat ,
Thank you for reporting this issue.
Bamboo Artifactory plugin version 3.3.0 was just released and includes a fix.
We'd appreciate your feedback for it.
Thank you for your patience.

**Comment by tobmat** [comment]
@RobiNino Thanks for the update.  We are in the process of upgrading now but I encountered another issue that I posted here.  Once that is resolved I can validate this one and give you feedback.  Thanks!

https://github.com/jfrog/bamboo-artifactory-plugin/issues/200

**Comment by tobmat** [comment]
@RobiNino build.name and build.number propertied look good.  I will close this issue.
