### ISSUE TITLE
Artifactory plugin for Bamboo cannot be enabled in Bamboo 9.0.1

### ISSUE THREAD

**Issue by Sven-O** [jfrog/bamboo-artifactory-plugin#192]
After upgrading Bamboo to version 9.0.1 the Jfrog add-on version 3.2.9 shows as incompatible. In the past, the add-on has still worked. This time the add-on cannot be enabled. It is not possible to find the 3.2.10 version in the Bamboo App UI either. I assume that I could download the 3.2.10 jar file and try it, but there are other reports that it wont work with Bamboo 9.x either. 

Go to the Manage add-ons panel and click "Enable" for the add-on. 
The add-on is expected to be enabled.

**Versions**
- Bamboo Artifactory plugin version: 3.2.9
- Bamboo operating system: Rhel 8
- Artifactory Version: 7.46.10
[ARtifactoryAddonIssue.docx](https://github.com/jfrog/bamboo-artifactory-plugin/files/9953597/ARtifactoryAddonIssue.docx)

Is this add-on intended to be supported with new Bamboo versions in the future?

**Comment by eyalbe4** [comment]
This is already being discussed in https://github.com/jfrog/bamboo-artifactory-plugin/issues/190 @Sven-O.
