### ISSUE TITLE
Bamboo 9.4.x support

### ISSUE THREAD

**Issue by holle** [jfrog/bamboo-artifactory-plugin#207]
Hi team,

has anyone checked whether the app runs under Bamboo 9.4.1 or later once it appears?
I know that LTS (9.2.7 as of now) is covered but sometimes you want the latest and greatest ;-)

Thanks in advance,
Holger

**Comment by mos9mu** [comment]
Also, any dates for releasing a DC Bamboo compatible version of this plugin?

**Comment by yahavi** [comment]
@holle 
Bamboo Artifactory plugin 3.3.3 has been released. This version was verified with Bamboo 9.4.2.
Feel free to upgrade - We'd appreciate your feedback on that.

Additionally, we highly recommend considering an upgrade to our new JFrog CLI-based Bamboo JFrog plugin, which can be found at https://marketplace.atlassian.com/apps/1231543/jfrog-for-bamboo
