### ISSUE TITLE
No Plugin with key 'org.jfrog.bamboo.bamboo-artifactory-plugin:maven3Task' is installed

### ISSUE THREAD

**Issue by fszilinski** [jfrog/bamboo-artifactory-plugin#35]
Hi, 

since I installed the new Version of the Plugin we receive "no Plugin installed" error. I already tried to disable/enable and uninstall/install the plugin again. In our plan we use the "Artifactory Maven 3" Task with "clean install" goals. Any ideas or a bug?

Bamboo Version: 5.14.3.1 build 51416 - 05 Dec 16
Plugin Version: 2.0.0
Build runs on EC2 Agent

Output Log-File
> 2017-01-09 11:48:59,620 INFO [bambooAgentMessageListenerConnector-1] [DefaultErrorHandler] Recording an error: Could not execute task  no Plugin with key 'org.jfrog.bamboo.bamboo-artifactory-plugin:maven3Task' is installed. : EC-EJC-JOB1

Log-Output from Bamboo:
> error	09-Jan-2017 11:44:33	Could not execute task  no Plugin with key 
'org.jfrog.bamboo.bamboo-artifactory-plugin:maven3Task' is installed. 
simple	09-Jan-2017 11:44:33	Running post build plugin 'Docker Container Cleanup' 
simple	09-Jan-2017 11:44:33	Running post build plugin 'NCover Results Collector' 
simple	09-Jan-2017 11:44:33	Running post build plugin 'Clover Results Collector' 
simple	09-Jan-2017 11:44:33	Running post build plugin 'npm Cache Cleanup' 
simple	09-Jan-2017 11:44:33	Running post build plugin 'Artifact Copier' 
simple	09-Jan-2017 11:44:33	Finalising the build... 
simple	09-Jan-2017 11:44:33	Stopping timer. 
simple	09-Jan-2017 11:44:33	Build EC-EJC-JOB1-16 completed.

**Comment by eyalbe4** [comment]
@fszilinski, 
Did you upgrade to version 2.0.0 of the plugin, using the upgrade procedure described [here](https://www.jfrog.com/confluence/display/RTF/Bamboo+Artifactory+Plug-in)?

**Comment by fszilinski** [comment]
Yes. At the moment I am following a more general problem described here: 
https://answers.atlassian.com/questions/37534625/bamboo-plugin-not-found-on-agents

It looks like something on Remote Agent Instance is not configured correct.

**Comment by fszilinski** [comment]
Ok, seems like adding the executable again to the remote agent instance solved the plugin problem. I created a new AMI from the new instance. 

My Problem now seems to be, that the "Resolve artifacts from Artifactory" function is not working anymore. My expectation was, that the maven settings.xml file get automatically created by choosing this option. Workarround is to add the settings.xml manually on initialization script of agent.

**Comment by eyalbe4** [comment]
@fszilinski.
When checking the "Resolve artifacts from Artifactory" checkbox, choosing "Resolution Artifactory Server URL" and a "Resolution repository", the build resolves the dependencies from the defined Artifactory repository, regardless of your settings.xml definitions.
I've just tested it following your message, and it seems to work.

**Comment by fszilinski** [comment]
This issue appeared several times on our bamboo remote elastic agents and we found the original problem that caused the plugin error. Our remote agent java process (not the instance) was started with low memory settings (Xmx=256m) that is written in file "/tmp/bamboo-agent-bootstrap-1.sh".

After loading several AddOn's the Artifactory Plugin caused a OutOfMemoryError error.
```
2017-10-06 10:18:42,185 ERROR [AgentRunnerThread] [ScanningPluginLoader] Unable to deploy plugin 'org.jfrog.bamboo.bamboo-artifactory-plugin' from 'Unit: /home/bamboo/bamboo-agent-home/plugins/user-installed/plugin.7243879669873312599.bamboo-artifactory-plugin-2.1.1.jar (1507285000000)'.
2017-10-06 10:18:42,186 ERROR [AgentRunnerThread] [ScanningPluginLoader] Because of the following exception:
java.lang.OutOfMemoryError: Java heap space
```

After some research howto increase the bamboo setup I found [this description](https://confluence.atlassian.com/bamkb/outofmemory-errors-in-bamboo-elastic-agent-826899144.html). Since we increased the XmX to 512MB it works like a charm!

**Comment by neurostream** [comment]
@fszilinski this scenario played out in my environment as well.

Bamboo 6.4.1 with default Local and Remote Elastic Agent settings.

The AMI spins up and can get through work that didn't include additional plugins.  If, however, a stage running an Elastic Agent had a task that invokes a plugin ( also the bamboo-artifactory-plugin specifically , via Generic Artifactory Deploy task, in my case ), then I would see the error reported by the build failure summary ( "No Plugin [...] is installed" ).

At first it seemed counterintuitive to associate this error message with an "Java heap space" limit, but it makes more sense now.  **_Your link referring to the sed replacement of the heap size resolved this for me as well._**

Thanks!

**Comment by DimaNevelev** [comment]
@fszilinski,
It seems that your solution works.
With your permission, I'm closing this issue for now.

**Comment by raj13aug** [comment]
Hi Guys,

I am getting an error with the latest version of the bamboo(7.0.4) and Jforg artifactory plugin(3.10) version.

I don't see OutOfMemory errors, and I have plenty of space available on a remote agent.

Could not execute task 'Get latest DDF FMF and HCFW config' no Plugin with key 'org.jfrog.bamboo.bamboo-artifactory-plugin:artifactoryGenericResolveTask' is installed.

(11 Aug 2020, 1:02:49 PM, Occurrences: 4, Agents: hcfw-regression-1 (2))

**Comment by barbelity** [comment]
@raj13aug please see @neurostream comment in this thread.
He describes the same issue as you are receiving, and solved it [with this guide](https://confluence.atlassian.com/bamkb/outofmemory-errors-in-bamboo-elastic-agent-826899144.html).
This solution applies only for elastic agents.
Is this your case?

**Comment by DanielWeeber** [comment]
I have the same problem as @raj13aug. Remote Agents, but not elastic. "Could not execute Task '' no plugin with key 'org.jfrog.bamboo.bamboo-artifactory-plugin:artifactoryGradleTask' is installed.

**Comment by raj13aug** [comment]
Hi @DanielWeeber,

It's working fine after increased memory on a remote agent.

https://confluence.atlassian.com/bamkb/outofmemory-errors-in-bamboo-server-or-in-remote-agent-307038120.html

Regards,
Nataraj.R
