### ISSUE TITLE
Supports for releasing from plan branches

### ISSUE THREAD

**Issue by AmrAbuAbdo** [jfrog/bamboo-artifactory-plugin#49]
Is there a way to generate a release from a bamboo plan branch?
We need such feature because we fire hot-fix releases from plan branches.
Is there a workaround or something?

**Comment by eyalbe4** [comment]
@AmrAbuAbdo,
This functionality is currently not implemented by the Artifactory Plugin.

**Comment by AmrAbuAbdo** [comment]
Do you have any plans to implement it?
What do you suggest to overcome this issue?
Thanks in advance :)

**Comment by eyalbe4** [comment]
Sure @AmrAbuAbdo,
We opened [BAP-411](https://www.jfrog.com/jira/browse/BAP-411) to track this task. 
We'll look into adding this functionality as part of the upcoming release.

**Comment by yahavi** [comment]
@AmrAbuAbdo,
Please try this: 
In "Build result summary" there is a small arrow on the left. Choose your job and there you'll see the "Artifactory Release Promotion" tab.

**Comment by AmrAbuAbdo** [comment]
@yahavi Thanks man, but this feature only applicable when you are browsing "Build Result Summary" of the main bamboo plan.
On the other hand, this feature is not available for Bamboo plan branches.

Thanks!

**Comment by yahavi** [comment]
@AmrAbuAbdo,
Indeed, in the latest released version v2.3.0 there isn't a "Artifactory Release & Promotion" tab in branch builds. 
However, we resolved this issue unintentionally in the latest snapshot version in the following commit: https://github.com/JFrogDev/bamboo-artifactory-plugin/commit/fb0c23a4b57feb423c77653460e6ba7d0a8a388f.
Here is the snapshot version which include the fix: 
https://oss.jfrog.org/oss-snapshot-local/org/jfrog/bamboo/bamboo-artifactory-plugin/2.3.x-SNAPSHOT/bamboo-artifactory-plugin-2.3.x-20180108.084103-11.jar

We will appreciate your feedback for it.
Thanks!

**Comment by simonbasle** [comment]
@yahavi has this changed with v2.3.0? I found out the issue today, but I'm fairly certain I had done a release&promotion from a branch other than `master` in the past for a maintenance release 😕

**Comment by eyalbe4** [comment]
@simonbasle,
There's a chance that this functionality worked for branch builds in some older Bamboo versions, but from looking at this [commit](https://github.com/JFrogDev/bamboo-artifactory-plugin/commit/fb0c23a4b57feb423c77653460e6ba7d0a8a388f) which fixed the issue, this is the only change done from the Artifactory Plugin side which can affect this. If indeed this used to work for branch builds, it could have stopped working as a result of a Bamboo API change.

**Comment by yahavi** [comment]
@AmrAbuAbdo & @simonbasle,
Bamboo Artifactory Plug-in v2.4.0 had been released.
Feel free to upgrade.

**Comment by efimovee** [comment]
@yahavi, @eyalbe4, 
Looks like it's broken again, at least in Bamboo 6.9.2 with Artifactory plugin 2.6.3/2.7.0.
There is no "Artifactory Release & Promotion" tab in plan-branches.
In Bamboo 6.6.2 with Artifactory plugin 2.6.2 with same settings, everything is fine.

**Comment by eyalbe4** [comment]
Thank you for raising this issue @efimovee!
Since @yahavi created https://github.com/jfrog/bamboo-artifactory-plugin/pull/75, I think we can close this issue.
Closing.
