### ISSUE TITLE
Why does generic deploy task need to be a final task?

### ISSUE THREAD

**Issue by obestwalter** [jfrog/bamboo-artifactory-plugin#55]
Hi, I was wondering, why this is the case - the [docs](https://www.jfrog.com/confluence/display/RTF/Bamboo+Artifactory+Plug-in#BambooArtifactoryPlug-in-TheArtifactoryGenericDeployTask) only say 

> Make sure to add the Generic Deploy task as a final step!

If I add it as a normal task, which is possible the build fails with "Artifactory Generic Deploy Task must run as a final Task!" - also without any explanation, why this is necessary.

From a user perspective this is counter-intuitive. I only want to upload something when my build was successful. I also might want to use that task as a build step in the middle of some process rather than only at the end.

Which technical limitation makes this necessary, or might it be possible to transform this into a "normal" task?

**Comment by barbelity** [comment]
Thank you for pointing us this issue @obestwalter.
You are right, we will further examine this behaviour and probably this limitation will be removed in our next release.
I will keep you updated with our findings.

**Comment by barbelity** [comment]
Hi @obestwalter, we have recently a removal of the limitation, which can be found here: https://github.com/jfrog/bamboo-artifactory-plugin/commit/a13e9e7168730261705c203db5edaf51546c648cl.
This is going to be part of our upcoming release in the next days.

Please let me know If you require this behaviour sooner, in such case I can create a SNAPSHOT version of the plugin and share it with you.

**Comment by obestwalter** [comment]
Hi @barbelity, that's great news. Thanks. No need for a preview version if you already plan a release soon.

**Comment by barbelity** [comment]
@obestwalter, I am happy to update that we released our plugin version 2.5.0.
It is now available for download at [Atlassian Marketplace](https://marketplace.atlassian.com/apps/27818/artifactory-for-bamboo?hosting=server&tab=overview) and [Bintray](https://bintray.com/jfrog/jfrog-jars/download_file?file_path=org%2Fjfrog%2Fbamboo%2Fbamboo-artifactory-plugin%2F2.5.0%2Fbamboo-artifactory-plugin-2.5.0.jar).

**Comment by obestwalter** [comment]
Thanks. As it is only compatible with 6.5 we have added motivation now to upgrade from 6.4.2 :+1:

**Comment by barbelity** [comment]
The new version of the plugin is also compatible with Bamboo version 6.4.1 and above, this information  is now updated at the marketplace and our [documentation](https://www.jfrog.com/confluence/display/RTF/Bamboo+Artifactory+Plug-in).

**Comment by obestwalter** [comment]
That's great. We just updated and are trying it out with one of our plans.

**Comment by obestwalter** [comment]
Works as advertised :+1:
