### ISSUE TITLE
Maven 3 task: JAVA_HOME is not correctly set.

### ISSUE THREAD

**Issue by efimovee** [jfrog/bamboo-artifactory-plugin#77]
We have a problem with Artifactory Maven 3 task and maven-javadoc-plugin:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project: MavenReportException: Error while creating archive: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set.

Looks like Bamboo Artifactory Plugin doesn't set JAVA_HOME 

There is a point about it on http://maven.apache.org/install.html
> Ensure JAVA_HOME environment variable is set and points to your JDK installation

`artifactory.task.override.jdk` isn't working too (https://www.jfrog.com/confluence/pages/viewpage.action?pageId=46108401#BambooArtifactoryPlug-in-ControllingtheBuildJDKusingBambooVariables)
I tried `artifactory.task.override.jdk.env.var=bamboo_capability_system_jdk_JDK_11` and `artifactory.task.override.jdk.env.var=bamboo.capability.system.jdk.JDK-11`
> The task is configured to use the 'bamboo_capability_system_jdk_JDK_11' environment variable for the build JDK, but this environment variable is not defined.`

I also tried `builder.artifactoryMaven3Builder.environmentVariables="JAVA_HOME=${bamboo_capability_system_jdk_JDK_11}"`
Doesn't work. `bamboo_capability_system_jdk_JDK_11` and `bamboo.capability.system.jdk.JDK-11`
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME=${bamboo_capability_system_jdk_JDK_11} doesn't exist or is not a valid directory.`

So we only can hardcode JDK-path in `builder.artifactoryMaven3Builder.environmentVariables="JAVA_HOME=/path/to/jdk"` or make changes in pom.xml (https://stackoverflow.com/a/54323506) for all projects

Meanwhile, the default Maven 3 plugin (https://docs.atlassian.com/bamboo/docs-0606/Maven) works fine.

**Comment by yahavi** [comment]
@efimovee
Bamboo Artifactory plugin 3.2.0 is released.
This version includes https://github.com/jfrog/bamboo-artifactory-plugin/pull/100 which contributed by @clarkperkins.
Feel free to upgrade - we'd also appreciate your feedback for that!

**Comment by eyalbe4** [comment]
Please read the Bamboo version compatibility matrix, before upgrading to version 3.2.o of tbe plugin.
