### ISSUE TITLE
Artifactory Gradle Capability randomly only availably on master/remote agents

### ISSUE THREAD

**Issue by robertlindner** [jfrog/bamboo-artifactory-plugin#80]
Hi, we have a problem with the Artifactory Gradle Plugin since upgrading to Bamboo 6.9.2 / Artifactory plugin 2.7.2

The Artifactory Gradle tasks, with "use gradle wrapper" selected, sometimes only show up as available on the bamboo masters default agent, but not on the remote agents and vice versa. All remote agents and the master do have the same JDKs installed.
In bamboo 6.8 the gradle tasks were available on all agents.

<img width="1045" alt="master_only" src="https://user-images.githubusercontent.com/14174677/65758504-7ed79380-e119-11e9-9e21-79fa1f5342fd.png">
<img width="1085" alt="remote_agent_only" src="https://user-images.githubusercontent.com/14174677/65758506-7ed79380-e119-11e9-804c-cc2cbe663547.png">

**Comment by yahavi** [comment]
@robertlindner 
Thanks for reporting this issue.
Do you still see it issue in the latest version?

**Comment by robertlindner** [comment]
No, since it was not working, and bamboo yaml specs did not support the gradle plugin anyways, we stopped using the plugin and invoke gradle from a shell task now.
